### ISSUE TITLE
The `getMainUrl()`, `getLayoutUrl()` and `getUuid()` follow the same logic that for the article

### ISSUE THREAD

**Issue by jdcaballerov** [openzim/python-libzim#11]
The `getMainUrl()`, `getLayoutUrl()` and `getUuid()` follow the same logic that for the article, the user code should implement a class inhering the `zim::writer::Creator` and provides those methods.

However, storing a url is not be big deal. We can move on with this.

_Originally posted by @mgautierfr in https://github.com/openzim/python-libzim/pull/3_

**Comment by kelson42** [comment]
@rgaudin Still a valid ticket?

**Comment by rgaudin** [comment]
Yes, this has not been done. The goal is to provide flexibility in subclassing `Creator` to get those information. It's not of much use at the moment, except for the main_url which must be set at Creator instantiation.

**Comment by rgaudin** [comment]
Obsolete now.
