### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by rgaudin** [openzim/python-libzim#117]
Here's a sample code demonstrating the memory issue we have on sotoki, using pylibzim.

We read a large XML file using sax, play with its data a bit then send it to the libzim. I imagine the data we store in the Item is not released. The issue might be in the `ContentProvider` though…

Without pylibzim:
![no-zim](https://user-images.githubusercontent.com/57929/130493136-1641b956-4613-45df-b663-b304dc3d07f9.png)

Adding content to ZIM:
![with-zim](https://user-images.githubusercontent.com/57929/130580509-3ccae8f9-abb6-48ca-a281-07cd2fbe7e1c.png)

The stable part at the end is the finish

```py
""" pylibzim leak tester

1.  Download and extract SO XML file
    wget http://tmp.kiwix.org/users_with_badges.xml.bz2
    bunzip2 -k users_with_badges.xml.bz2

2.  prepare environ
    python3.8 -m venv pyleak
    source pyleak/bin/activate
    # macOS: replace manylinux1 with macosx_10_9
    pip install libzim-1.0.0.dev2-cp38-cp38-manylinux1_x86_64.whl
    pip install matplotlib memory-profiler

3.  Launch without ziming
    mprof run -o no-zim.dat -E python ./test-leak.py ./users_with_badges.xml --no-zim

4.  Observe that memory consumption is stable
    mprof plot no-zim.dat

5.  Launch with pylibzim
    mprof run -o with-zim.dat -E python ./test-leak.py ./users_with_badges.xml

6.  Observe that it's leaking
    mprof plot with-zim.dat
"""

import pathlib
import uuid
import sys
import xml.sax.handler

import libzim.writer


class UserItem:
    def __init__(self, content):
        self.content = content

    def get_path(self):
        return uuid.uuid4().hex

    def get_title(self):
        return ""

    def get_mimetype(self):
        return "text/html"

    def get_hints(self):
        return {}

    def get_contentprovider(self):
        return libzim.writer.StringProvider(self.content)


class Walker(xml.sax.handler.ContentHandler):
    def __init__(self, no_zim=False):
        self.no_zim = no_zim
        if not self.no_zim:
            self.creator = libzim.writer.Creator(
                filename="test-leak.zim",
            ).config_verbose(True)

    def startDocument(self):
        self.seen = 0
        if not self.no_zim:
            self.creator.__enter__()

    def endDocument(self):
        if not self.no_zim:
            self.creator.__exit__(None, None, None)

    def startElement(self, name, attrs):
        if name == "row":
            # store xml data until we're through with the <row /> node
            self.user = dict(attrs.items())

        elif name == "badges":
            # prepare a space to record badges for current user
            self.user["badges"] = {"1": {}, "2": {}, "3": {}}

        elif name == "badge":
            # record how many times a single badge was set on this user
            if attrs.get("Name") in self.user["badges"][attrs.get("Class")].keys():
                self.user["badges"][attrs.get("Class")][attrs.get("Name")] += 1
            else:
                self.user["badges"][attrs.get("Class")][attrs.get("Name")] = 1

    def endElement(self, name):
        if name == "row":
            # only if processor_callback retained it (to be included)
            self.processor(item=self.user)

            self.seen += 1
            if self.seen % 1000 == 0:
                print(f"Seen {self.seen}")

    def processor(self, item):
        content = str(item)
        if not self.no_zim:
            self.creator.add_item(UserItem(content=content))


def main(fpath, no_zim=False):
    print(f"Starting with {no_zim=}")
    parser = xml.sax.make_parser()  # nosec
    parser.setContentHandler(Walker(no_zim=no_zim))
    parser.parse(fpath)
    parser.setContentHandler(None)
    print("Done.")


if __name__ == "__main__":
    usage = f"{sys.argv[0]} XML_FILE [--no-zim]"
    if len(sys.argv) < 2:
        print(usage)
        sys.exit(1)

    fpath = pathlib.Path(sys.argv[1])
    if not fpath.exists():
        print(f"{fpath} does not exist.")
        print(usage)
        sys.exit(1)

    no_zim = "--no-zim" in sys.argv

    sys.exit(main(fpath, no_zim))

```

**Comment by rgaudin** [comment]
Using `FRONT_ARTICLE` on all of them:
![with-zim-front](https://user-images.githubusercontent.com/57929/130580241-4596ec61-9051-4f07-9059-56820bd3adc4.png)

Using `FRONT_ARTICLE` and a custom title/path from the content
![with-zim-front-title](https://user-images.githubusercontent.com/57929/130580325-29ee5e7f-176c-4504-b95d-20fe92b3d2ef.png)

The missing stable part was due to a typo so it crashed trying to call finish…

**Comment by mgautierfr** [comment]
It seems there is no memory leak (sorry).

Each entry need a dirent and a dirent size is 160 Bytes (plus the size of the path, 32). So each item need 192 Bytes.
I've change a bit the your test program to create dummy items (no xml parsing) and put only 500 000 items and no compression to avoid the "noise" of the compression part (and speed up a bit everything).

![graph_memory_500k](https://user-images.githubusercontent.com/86161/130628664-843e77be-76f9-4541-8c31-88c3da90018d.png)

We allocate dirents by batch of 65535 (0xFFFF) so ~10MB. You can clearly see those "jumps" in the graph (and there is one at the beginning, "merged" with other initial allocation).
(Other jumps, around 17s, is probably due to some internal std allocation).

Then we slowly increase the memory for the path to reach an extra 6Mb. There is 2Mb that can be easily explained to store the path (32*0xFFFF ~ 2Mb).

The 4 other Mb can be explain by the fact we need to store those dirent's pointers in two `std::set` and one or two `std::vector` (depending if we have FRONT_ARTICLE or not). It is not clear how much memory is used by a set but from this blob post https://lemire.me/blog/2016/09/15/the-memory-usage-of-stl-containers-can-be-surprising/ (the only one I've found on the subject). We can think it is yet again 32B per items per set and 8B per vector, so the 4Mb).

At the end, we can see that we go from around 25Mb to 155Mb, so 130Mb increase. Which is coherent with (500000*(160+32+32+32+8) = 125Mb)

I'm afraid there is no easy fix here (if there is one). I've to think about this but I've no idea for now.

**Comment by rgaudin** [comment]
OK, well at least if explain why we get close to 4GB on the whole users thing, as the graph shows:

```
(160+32+32+32+8) * 14839000 = 3,917,496,000  # 3.65 GiB
```

**Comment by rgaudin** [comment]
@mgautierfr are those 264b (160+32+32+32+8) identical for redirects? Is there additional allocation for FRONT_ARTICLE? I'm trying to figure out the requirements for sotoki. Will send in a list of the entries we try to put in.

**Comment by mgautierfr** [comment]
- 160 is the size of the dirent. We use the same structure for classic and redirect (I'm looking for reducing this size).
- The first 32 is the size of the path (size of a uuid here). In real use case, we need to store the size of the path and the title. (both for classic and redirect)
- Second 32 is the estimation of the size taken to store dirent in a set containing all dirent (both classic and redirect)
- Third 32 is the estimation for storing unresolved redirect. So obviously for redirect added before the target dirent.
- 8 is a pointer to the dirent stored to compute the title ordered list (all dirents)
- For front_article we have another 8 byte pointer stored. (front_article, classic or redirect)

**Comment by rgaudin** [comment]
Thanks @mgautierfr, here are the sotoki numbers

```
Nb FRONT Items:
    21286479    # questions with answers and comments
    53500000    # users (we don't store those without interactions)

    T: 74,786,479
    > @272b = 20,341,922,288b  # 18.94 GiB

nb NO-FRONT Items:
    100         # questions listing pages
    100         # users listing pages
    100         # assets (approx.)
    90000         # Tags questions listing (approx. 61K tags, up to 133pg/tag)
    1697        # tags listing pages (61059/36)
    2184316     # Users images
    17153       # questions images (extrapolated)

    T: 2,293,466
    > @ 264b = 605,475,024b  # 577.43 MiB

Nb Redirect Item
    31692495    # answers
    10          # pagination

    T: 31,692,495
    > @264b = 8,366,818,680  # 7.79 GiB
```

GRAND TOTAL: 18.94 GiB + 577.43 MiB + 7.79 GiB = **27.3 GiB**


In theory, adding our 18GiB for redis, we'd be around **45+GiB** which sound *manageable*.

I suppose there was additional leak in the scraper leading the last failure of the scraper (like the lxml one) and maybe I should finish that leak hunt and re-run on 60GB or RAM.

**Comment by kelson42** [comment]
FYI, it seems that WPEN maxi can not be scraped anymore with 15GB of memory, see https://farm.openzim.org/pipeline/492375ee90bad68f49dec116/debug. This is with libzim6, but AFAIK libzim7 is not better regarding writer memory consumption. All of this tends to lead to a better writer memory efficiency. Seems necessary.

**Comment by rgaudin** [comment]
@mgautierfr, @kelson42 , there was a typo in my calculation above (not 53M users but 5.3!). I've fixed the total and we're now looking at **15GiB+ for pylibzim** usage.

@mgautierfr, am I right in understanding that in those 264/272 bytes, we are using 32 to store both path and title (uuid hex, no title in this example) and that in a real-case scenario, those 32 are *dynamic* and would be as many as required to store both path and title encoded in UTF-8?

I understand UTF-8 stores characters with a variable number of bytes (1-4) depending on where those are in the Unicode table. Can you confirm this assumption so I can script an estimate of the impact of those 26.6M Items with meaningful titles and the ~60M paths ?

**Comment by mgautierfr** [comment]
The PR openzim/libzim#616 greatly reduce the size of the Dirent from 160B to 39B.

The same run as my previous comment uses now around 65Mb (90-25) instead of 130Mb
The used sized is now (500000*(39+32+32+32+8) = 68Mb)

![graph_memory2_500k](https://user-images.githubusercontent.com/86161/130813542-3abd46df-4749-4038-9fed-672c18543536.png)

> I right in understanding that in those 264/272 bytes, we are using 32 to store both path and title (uuid hex, no title in this example) and that in a real-case scenario, those 32 are dynamic and would be as many as required to store both path and title encoded in UTF-8?

Yes. For the test path is the hex dump of a uuid so a 32 char long string. In real-case scenario, the needed size will depend of the size of the utf8 encoded path+title.

**Comment by mgautierfr** [comment]
As said in https://github.com/openzim/libzim/issues/618#issuecomment-911757549, it seems the bug was on zimscrapperlib.
If I interpret @rgaudin's comment correctly it seems that he succeed to fix the issue (but I don't know if the fix has been published or not)

**Comment by kelson42** [comment]
@mgautierfr Please open a dedicated ticket, actually he didn't fixed it and this is the highest priority ticket for the moment.

**Comment by rgaudin** [comment]
Closing this as what was discussed here has been sorted out.
