### ISSUE TITLE
Help installing python libzim in termux

### ISSUE THREAD

**Issue by sobaee** [openzim/python-libzim#130]
Hello dear developer

I failed to install python-libzim 1.0.0 in termux mobile

Termux use libzim library 7.0.0, python 3.9.0

Please help with any information could help

It gives me this error: 

ERROR: Could not find a version that satisfies the requirement libzim==1.0 (from versions: 0.0.1, 0.0.2, 0.0.3, 0.0.3.post0, 0.1, 1.0.0)
ERROR: No matching distribution found for libzim==1.0

**Comment by kelson42** [comment]
@sobaee This means that your libzim is not installed properly. What is your exact system/architecture? What is the exact command your rung with the bull log?

**Comment by rgaudin** [comment]
I think both the README and the [PyPi listing](https://pypi.org/project/libzim/#files) are clear about what you can get from a pip install.

I suppose your termux mobile is not x86_64. For it to work, you'd need to build it (see README).

**Comment by sobaee** [comment]
> I think both the README and the [PyPi listing](https://pypi.org/project/libzim/#files) are clear about what you can get from a pip install.
> 
> I suppose your termux mobile is not x86_64. For it to work, you'd need to build it (see README).

I appreciate your quick answer

I really thought about building it

But I only need to build python libzim not libzim library itself (because termux has libzim library 7.0.0), and I couldn't find how to build python libzim!! Not in readme.md not in pypi

So please provide me the way how I build python libzim.

**Comment by rgaudin** [comment]
Just `python setup.py build_ext -i` (or the `invoke build-ext` shortcut mentioned in the README). Make sure to adjust you `LD_LIBRARY_PATH` env if the build script can't find your libzim so file.

Let us know how it goes

**Comment by sobaee** [comment]
Error:


Traceback (most recent call last):
  File "/storage/emulated/0/pyglossary-master/libzim/setup.py", line 39, in <module>
    from ctypes.util import find_library
  File "/data/data/com.termux/files/usr/lib/python3.9/ctypes/__init__.py", line 8, in <module>
    from _ctypes import Union, Structure, Array
ImportError: dlopen failed: cannot locate symbol "ffi_closure_free" referenced by "/data/data/com.termux/files/usr/lib/python3.9/lib-dynload/_ctypes.cpython-39.so"...

**Comment by rgaudin** [comment]
You need to install Cython first, then build the extension, then either install or copy the libzim so into the right folder and build a wheel that you can re-install later.

I suggest you follow the linux-related steps from https://github.com/openzim/python-libzim/blob/master/.github/workflows/release.yml

**Comment by sobaee** [comment]
> You need to install Cython first, then build the extension, then either install or copy the libzim so into the right folder and build a wheel that you can re-install later.
> 
> I suggest you follow the linux-related steps from https://github.com/openzim/python-libzim/blob/master/.github/workflows/release.yml

Cython already installed by pip install cython

Libzim so is in the the right place:  /data/data/com.termux/files/usr/lib/libzim.so

And I already:
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/data/data/com.termux/files/usr/lib/


Linux step is complicated steps for me,  Iam just a beginner who want to install python libzim

I also don't know how to setup "env"

**Comment by sobaee** [comment]
I also installed gcc for termux and it failed also to build and install python libzim

**Comment by sobaee** [comment]
Finally guys I managed this by using linux amd64 in termux then install python-libzim 1.0.0 in python 3.9 (build python 3.9 manually not apt install)

This the link for termux amd64 how to do it but change to the amd64 not i686 (x86):
https://m.youtube.com/watch?v=Ucc1sNqIoc8

**Comment by sobaee** [comment]
Thanks to @xtkoba

I managed to install python-libzim 1.0.0 in termux.

Here is what I did:

apt install rust binutils libzim

pip install wheel cython

export CARGO_BUILD_TARGET=aarch64-linux-android && pip install cryptography

export PATH='/data/data/com.termux/files/usr/bin'

export LD_LIBRARY_PATH='/data/data/com.termux/files/usr/lib'

pip install libzim==1.0

**Comment by rgaudin** [comment]
Good to know ; thanks
