### ISSUE TITLE
Add easy flag to disable tests that require internet access

### ISSUE THREAD

**Issue by legoktm** [openzim/python-libzim#132]
Debian package builds do not have any internet access, and fail when they try to download the test data. It would be nice if there was some simple environment variable that can be set to skip those tests when set.

For example, in https://github.com/earwig/mwparserfromhell/commit/a64bae35c9395389d2ef96adc37d828cd217b911 we added a "NOWEB" setting to disable a test that required internet access.

**Comment by kelson42** [comment]
How have we solve this for libzim?

**Comment by rgaudin** [comment]
We could but I don't see the point as all reader tests uses ZIM files that we won't add to sources. What would be the point of launching tests if it doesn't test anything?

**Comment by kelson42** [comment]
@legoktm I close the ticket, please let us know if you need more.

**Comment by legoktm** [comment]
> We could but I don't see the point as all reader tests uses ZIM files that we won't add to sources. What would be the point of launching tests if it doesn't test anything?

@rgaudin More than half of the tests don't require any internet access AFAICT:
```
============================= test session starts ==============================
platform linux -- Python 3.9.9, pytest-6.2.5, py-1.10.0, pluggy-0.13.0
rootdir: /<<PKGBUILDDIR>>, configfile: pyproject.toml
collected 86 items

tests/test_libzim_creator.py ........................................... [ 50%]
....                                                                     [ 54%]
tests/test_libzim_reader.py .ssssssssssssssssssssssssssssssssssssss      [100%]

======================== 48 passed, 38 skipped in 3.76s ========================
```

So I think it is reasonable to have the Debian package run whatever tests it can while building, and secondly have some flag that allows skipping the ones that require internet access.

**Comment by rgaudin** [comment]
> > We could but I don't see the point as all reader tests uses ZIM files that we won't add to sources. What would be the point of launching tests if it doesn't test anything?
> 
> 
> 
> @rgaudin More than half of the tests don't require any internet access AFAICT:
> 

As explained above, those are the writing tests only (creating ZIM files, not reading them).
The only reader test checks an blank self-created one.
                                                        
> So I think it is reasonable to have the Debian package run whatever tests it can while building, and secondly have some flag that allows skipping the ones that require internet access.

Ok then.
