### ISSUE TITLE
Segfault adding a duplicate illustration

### ISSUE THREAD

**Issue by rgaudin** [openzim/python-libzim#141]
I believe it can be considered a *bug* that we now (libzim 7.2.1) raises a RuntimeError when adding a duplicate of Entry, Metadata or Redirection but not for Illustration. Trying to add another (or the same) illustration for the same size segfaults.

Not sure if this gets fixed in here or at libzim level though.

**Comment by mgautierfr** [comment]
This is the consequence of https://github.com/openzim/libzim/pull/690/commits/1f27949a80b1f4a9d49c2749fc513b9853f1bcfe
We will probably not change this in libzim. python wrapper must catch the exception and handle it correctly (this is a bug in the scapper if it adds twice the "same" entry)

**Comment by kelson42** [comment]
@audiodude @rgaudin So we should open a new ticket and make a new libzim release?
