### ISSUE TITLE
Debian package fails to compile

### ISSUE THREAD

**Issue by kelson42** [openzim/python-libzim#160]
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1028780

**Comment by kelson42** [comment]
I can not investigate right now, but:
* either there is a problem in getMediaCount() declaration in libzim OR
* Debian compiles against an older version of the libzim and the we have a requirement problem (in package definition and in compilation script): we should require libzim 8.1.0+

**Comment by rgaudin** [comment]
https://salsa.debian.org/debian/python-libzim/-/blob/master/debian/control specifies ` libzim-dev (>= 8.1.0),`

**Comment by paulgevers** [comment]
> https://salsa.debian.org/debian/python-libzim/-/blob/master/debian/control specifies ` libzim-dev (>= 8.1.0),`

That is currently insufficient as you can see from the name `8.1.0+really8.0.0-1`. The package of `zimlib` had to be reverted to 8.0.0 but package version can only go up: https://tracker.debian.org/news/1408038/accepted-zimlib-810really800-1-source-into-unstable/

**Comment by kelson42** [comment]
Seems to be a pure packaging problem - but not sure about the root cause - not sure there is anything we can do here.

**Comment by xvitaly** [comment]
> It is not breaking ABI in patch release (we re-add a missing method). It is undo a breaking ABI (introduced in a minor release) with a patch release.

Looks good for me.

**Comment by kelson42** [comment]
Fixed in libzim and available in libzim 8.1.1
