### ISSUE TITLE
Add support for arm64

### ISSUE THREAD

**Issue by rgaudin** [openzim/python-libzim#164]
Now that libzim is built on arm64 for both linux (glibc) and macOS, we need to publish for those platform as well.

Only nightlies are available at the moment.
arm64 for musl is not ready yet

**Comment by kelson42** [comment]
Blocked by https://github.com/kiwix/kiwix-build/issues/585

**Comment by rgaudin** [comment]
This has been fixed. We now support arm64 on macOS and aarch64 on Linux
