### ISSUE TITLE
Writing part must be in a submodule `writer`

### ISSUE THREAD

**Issue by mgautierfr** [openzim/python-libzim#17]
From the user point of view :
- `zim` module contains things to read a zim
- `zim.writer` module contains things to create a zim.

Class names must not include the `Zim` :
- `ZimArticle` -> `zim.writer.Article`
- `ZimCreator` -> `zim.writer.Creator`
- `ZimFileReader` -> `zim.File`, `zim.Reader` or `zim.FileReader` (I'm not sure what is best)
- `zimFileArticle` -> `zim.Article`
- ...

**Comment by jdcaballerov** [comment]
Having a [package hierarchy in Cython is basically doing two extensions](https://github.com/cython/cython/wiki/PackageHierarchy). That means that is not as in normal python as creating a dir and putting the files.

Taking into account that the CI / CD supports many options (static, dynamic, from source, with cython, without, etc)  this modification at this point could break it.

if going from

```python3
from libzim import ZimFileReader, ZimCreator
``` 

to

```python3
from libzim import ZimFileReader
from libzim.writer import ZimFileReader
```

if definitively this is desired , then creating a new package could be easier for you with the existent code under the branch `reader` https://github.com/openzim/python-libzim/tree/reader

**Comment by pirate** [comment]
Adding another layer of hierarchy to the extension is pretty easy in theory (1-2hr maybe?), but I think it can be done as a separate task:

```diff
ext_modules = cythonize([
        Extension(
            "libzim",
            sources=["libzim/**/*.pyx","libzim/**/*.cxx"],
-           include_dirs=["libzim"],
+           include_dirs=["libzim/reader", "libzim/writer"],
            libraries=["zim"],
            ...
        )
    ],
    compiler_directives={'language_level' : "3"},
)
```
+ some rejiggering of `.gitignore` and `Manifest.in`
