### ISSUE TITLE
glibc version mismatch building wheel on py37 aarch64

### ISSUE THREAD

**Issue by rgaudin** [openzim/python-libzim#170]
[this run](https://github.com/openzim/python-libzim/actions/runs/5542032499/jobs/10116191493) failed with

```
 auditwheel: error: cannot repair "/tmp/cibuildwheel/built_wheel/libzim-3.1.0-cp37-cp37m-linux_aarch64.whl" to "manylinux_2_28_aarch64" ABI because of the presence of too-recent versioned symbols. You'll need to compile the wheel on an older toolchain.
```

**Comment by rgaudin** [comment]
Issue is serious as it concerns all our aarch64 wheels.

Due to [glibc-usage](https://sourceware.org/glibc/wiki/Release), we have decided to support the `manylinux_2_28` [platform](https://packaging.python.org/en/latest/specifications/platform-compatibility-tags/) for Python 3.8-3.11 (3.7 is now EOL).
This means that our binary libzim (and the wrapper) should be compatible (and thus use at most) glibc 2.28.

For this reason, we are building libzim on Ubuntu bionic (glibc 2.27) and our wrapper is built on [manylinux_2_28](https://quay.io/repository/pypa/manylinux_2_28_aarch64) (glibc 2.28).

pylibzim 3.1.0 (May 1st 2023) uses libzim 8.2.0 ([release](https://download.openzim.org/release/libzim/libzim_linux-aarch64-bionic-8.2.0.tar.gz))
- was [was working](https://github.com/openzim/python-libzim/actions/runs/4852111841): auditwheel did not complain.
- produced the [correct wheels](https://pypi.org/project/libzim/3.1.0/#files). `aarch64` ones are actually `2_24` compatible (`auditwheel` renames to match the minimum satisfying version)

Rebuilding with libzim 8.2.0 works as expected but 8.2.1 doesn't.

[`auditwheel`](https://github.com/pypa/auditwheel) finds symbols requiring glibc 3.4 which is not acceptable (Debian 12+/ Ubuntu 22.04+/ Fedora 35+). This is due to the recent version of GCC (libstdc++ declaring `GLIBCXX_3.4.29`) used by [the cross-compilation toolchain](https://github.com/tttapa/docker-arm-cross-toolchain) introduced in https://github.com/kiwix/kiwix-build/pull/615

I've rebuilt libzim (`main`) and all its dependencies using the previous compiler and it produces an acceptable [libzim](http://tmp.kiwix.org/ci/libzim_linux-aarch64-bionic-2023-08-01.tar.gz) that works as expected.

Follow-up action (@mgautierfr) is thus to fix this _regression_ on kiwix-build. Beside pylibzim, it is likely that it's not possible to link libzim at all on focal neither. `zim-tools` and `kiwix-tools` are not affected as those are static binaries.

## Which platform to support?

It's important to document which version we want to support and why.

There is currently no Kiwix/openZIM policy AFAIK but my rule has been: support only still-maintained Python releases. Regarding system (important here as we're distributing a binary), support earliest still maintained Debian version.

- [Python](https://en.wikipedia.org/wiki/History_of_Python#Table_of_versions): 3.8+ up to October 2024
- [Debian](https://en.wikipedia.org/wiki/Debian_version_history#Release_table) 10 Buster+ up to June 2024

Kiwix-build recently switched to building on Ubuntu 20.04 focal. Focal uses glib 2.31, as well as Debian 11 Bullseye (as well as Fedora 32+).

**Comment by kelson42** [comment]
@rgaudin It seems there is no blicker to implement this ticket anymore? Or domwe have another ticket on kiwix-build which needs to be implememted?

**Comment by rgaudin** [comment]
This is being tested in the CI as we speak…

**Comment by rgaudin** [comment]
Fixed and merged
