### ISSUE TITLE
Only depend on delocate on needed platforms

### ISSUE THREAD

**Issue by legoktm** [openzim/python-libzim#205]
My reading of setup.py is that `delocate` is only needed on Windows. I think we use a platform specifier to only add the dependency on Windows? https://packaging.python.org/en/latest/specifications/dependency-specifiers/#environment-markers

(delocate isn't packaged in Debian so I've patched out the dependency for now)

**Comment by rgaudin** [comment]
Ah shoot, sorry about that ; I hesitated and figured it wouldn't hurt. I was wrong

**Comment by rgaudin** [comment]
@legoktm testing the fix ; will you require a new release?

**Comment by legoktm** [comment]
> @legoktm testing the fix ; will you require a new release?

Thank you and nope, I've already patched Debian to skip the dependency.
