### ISSUE TITLE
Type stubs questions

### ISSUE THREAD

**Issue by benoit74** [openzim/python-libzim#207]
While adding type stubs helped a lot, I now have few more issues.

First with
```
from libzim.writer import Hint
```
This causes pyright to say `warning: Import "libzim.writer" could not be resolved from source (reportMissingModuleSource)`. Would it be possible to get rid of this warning by setting something in python libzim and avoid clutering our projects with ignores on this?

Second, on a `item` which is a `libzim.writer.Item`, we cannot use `item.content` or `item.mimetype` while they work in reality. This is somehow circumvented in python-scraperlib. Not sure we need to fix this, but good to discuss. See also https://github.com/openzim/python-scraperlib/issues/196 and https://github.com/openzim/python-scraperlib/issues/197

**Comment by rgaudin** [comment]
> Would it be possible to get rid of this warning by setting something in python libzim and avoid clutering our projects with ignores on this?

No ; and that's not something we'd want if you think about it

> Second, on a item which is a libzim.writer.Item, we cannot use item.content or item.mimetype while they work in reality.

Sounds like a hint issue. Can you open a dedicated ticket with the actual code showcasing it?

**Comment by benoit74** [comment]
> Sounds like a hint issue. Can you open a dedicated ticket with the actual code showcasing it?

This is indeed only a python-scraperlib issue, mostly related to https://github.com/openzim/python-scraperlib/issues/196, will close this issue then.
