### ISSUE TITLE
Reading a ZIM file from project Gutenburg

### ISSUE THREAD

**Issue by sleepingcat4** [openzim/python-libzim#211]
I had downloaded the ZIM files for project Gutenberg and I want to understand its structure and also read its content in the memory and then write them into a text file. But, I am confused because its my first time working with this file format and I tried searching and trying to find docs but nothing helped or came-up. 

Can someone provide some beginner assistance? help is much appreciated!

**Comment by benoit74** [comment]
I don't really get what you mean by "structure". ZIM structure is not meant to be comfortable exploring manually, it is not its purpose, but it is meant to be efficient to retrieve data by ZIM readers (end-user application reading / searching the offline content).

Can you elaborate a bit on what you would like to do? Just load all files present inside the ZIM in memory?

**Comment by kelson42** [comment]
@sleepingcat4 Look at themwww.openzim.org for the spec. Zimdump (in the ZIM tools will help you do dump any content).

**Comment by sleepingcat4** [comment]
@benoit74 @kelson42 thanks for the links and quick response. I was thinking ZIM to be same as XML formats. 

I wanted to read ZIM files and extract the content. For example: I have a book Alice in Wonderland or a bulk file from Project Gutenberg. Obviously to access them I have to use a ZIM reader like you mentioned. But, that's inefficient if I want to make a dataset for AI in embeddings and other tasks. I was thinking if I could read the content and then write them in JSON or text format, I could easily use for my AI project. 

is there any guides or docs or code you guys can point me to or help with?

**Comment by benoit74** [comment]
The ZIM format is indeed not targeted to this usage at all. So we do not have docs about it. Not speaking about the fact that inside the ZIM documents are still in their original format (ePub, PDF or HTML) so you will still have to parse them as well.
I keep the issue open should someone have better suggestions ^^

**Comment by sleepingcat4** [comment]
@benoit74 is there a way to extract the HTML or pdf content from the ZIM files?

**Comment by rgaudin** [comment]
@sleepingcat4 As indicated in the openZIM spec, ZIM entries are identified by a path, similar to an URL path.

You can iterate over all entries like this:

```py
 zim = Archive("test.zim"))
                                                                                                                                                                 
 for index in range(0, zim.all_entry_count):
    entry = zim._get_entry_by_id(index)
 ```
  
You'll easily be able to retrieve the entry metadata (path, title, mimetype, size) and content. Check the README for that.

Once you have the `bytes` data of an entry, the rest is up to you: save it, pass it to a library, whatever.

Note that the few last entries (with path starting with `X/` are the indexes and not content from gutenberg).

Also note that as suggested by @kelson42, we have a tool called `zimdump` (available at https://download.openzim.org/release/zim-tools/) that extracts a ZIM into files on the filesystem. That might be a better starting point than python-libzim.
