### ISSUE TITLE
don't print filename on Creator()

### ISSUE THREAD

**Issue by rgaudin** [openzim/python-libzim#33]
I think it's a debug value that's no longer needed.

https://github.com/openzim/python-libzim/blob/2cdfa1c3deef3672099de8b9ebfac15940ec6b87/libzim/writer.py#L138-L139

**Comment by coderpaddy** [comment]
Do I just clone, attempt to fix, and make a pull request?

**Comment by coderpaddy** [comment]
made a pull request with the fix :D
