### ISSUE TITLE
get_article shouldn't raise RuntimeError

### ISSUE THREAD

**Issue by rgaudin** [openzim/python-libzim#38]
Currently, `ReadArticle.get_article()` raises a `RuntimeError` should the URL be incorrect. I believe we should either:

* Add an `.has_article(url)` methods that returns a boolean informing about the existence of the article
* Raise a custom, usable Exception like `ArticleNotFound` or something.

**Comment by mgautierfr** [comment]
Yes, `RuntimeError` is a base, generic exception. We could raise a more specific one.
However, with the planned change in the api `openzim/libzim#345`, this will change. We should wait for the new api to decide what to do.

**Comment by rgaudin** [comment]
Reading [cython doc](http://docs.cython.org/en/latest/src/userguide/wrapping_CPlusPlus.html#exceptions) and [this SO answer](https://stackoverflow.com/a/29002414) (and followings), it seems that we'd still have to declare and map the actual exception as the default behavior is to map everything (but a few standard ones) to `RuntimeError`.

So should we raise a custom (python for now) `NotFound(RuntimeError)` exception until https://github.com/openzim/libzim/issues/345 gets implemented and we map the actual `NotFound`?

**Comment by mgautierfr** [comment]
Indeed, we will need a custom exception handler both with the new api and the current one.

But I'm not sure that we should spend time on this now as it will change in a close future.
