### ISSUE TITLE
Get the number of results (from `get_matches_estimated()

### ISSUE THREAD

**Issue by jdcaballerov** [openzim/python-libzim#5]
> > * shouldn't we get a generator on `reader.search()` ? Do the libzim returns a list as-is? It's frequent to have thousands of results on large ZIM files.
>
> I did the same as node-libzim getting 10 results and passing back a string vector. File.h returns Search class unique pointers.
> ```
>  std::unique_ptr<Search> search(const std::string& query, int start, int end) const;
>  std::unique_ptr<Search> suggestions(const std::string& query, int start, int end) const;
> ```

Ah ok I see. that's unfortunate. I didn't realized you hardcoded that. We should definitely be able to set those. But we'd need the number of results (from `get_matches_estimated()`) as well. How do you plan to address that?

**Comment by jdcaballerov** [comment]
@rgaudin Can you clarify How's the API use of `get_matches_estimated()` to close this feature ?? 

I can already use the iterator from Cython for both search and suggestions (`File.h`)

The first number is the result of `get_matches_estimated()`

<img width="510" alt="Screen Shot 2020-04-10 at 16 34 28" src="https://user-images.githubusercontent.com/743513/79024699-5eb57200-7b49-11ea-8bed-32dc49b7457d.png">

**Comment by rgaudin** [comment]
Thanks for this.

* Why is it named `file_search()` and not `search()` ? Do you intend to keep both versions?
* I can't see how we can practically avoid having two methods to get the results count… do you?

Otherwise, we'd need better names like `get_search_results_count()` and `get_suggestions_results_count()`

**Comment by jdcaballerov** [comment]
I have `file_search` since I haven't deleted the old `search` version waiting for your approval. The other works from C++ sending string vectors of 10, this one runs in Cython using the libzim search object directly. 

If you agree then I'll only keep this and delete the C++ search code from the wrapper and add the counts as separate.

**Comment by jdcaballerov** [comment]
Done https://github.com/openzim/python-libzim/commit/054e7638fb398a0942a988e3122172acd1645c61
