### ISSUE TITLE
Cannot create a ZIM without an index

### ISSUE THREAD

**Issue by rgaudin** [openzim/python-libzim#52]
At the moment, we cannot create a ZIM file without creating an index.

I'm not sure about the use cases for this (as we can opt-out individually on all articles) but it's an option in mwoffliner so I'm asking. libzim2 plans great improvements to indexes but I don't think it makes it mandatory.

@mgautierfr @kelson42 ?

**Comment by kelson42** [comment]
We have two Xapian indexes titles+ft. There is missing clear way IMO to decide which one we want in the final ZIM.

**Comment by rgaudin** [comment]
Sorry for misleading you with that.
zimwriterfs has the `--withoutFTIndex` option which clearly request not to produce a full-text index (uses `zim::writer::setIndexing`.

Actually, I was wrong in saying we can't, it's just that we default to `eng` should no language be passed but we can explicitly set it to `""` and then the FT index is not created.

Closing this. Are we happy with this default? (I am).
