### ISSUE TITLE
Libzim for Termux app in android

### ISSUE THREAD

**Issue by sobaee** [openzim/python-libzim#77]
I can't install libzim in Termux app (aarch64)
I already installed app prerequisites and dependencies.
You may tell me whats the required versions of the dependecies, or how to install it manually from the source.

 
Please help!

**Comment by sobaee** [comment]
@kelson42 
Thanks

So, Do you have any suggestion about my question?

**Comment by rgaudin** [comment]
libzim binary is only [distributed](http://download.openzim.org/release/libzim/) for linux-x64 and macOS-x64 and so is the bundled libzim provided in the python binding.

Please go to https://github.com/openzim/libzim and see if you can compile the library. Once this is done and installed, you'll have to install the python binding using the source

```sh
python3 setup.py build_ext -i
python3 setup.py install
```

**Comment by sobaee** [comment]
Thank you Termux
Really, I can't thank you enough.
It works perfectly.

apt install libzim
pip install libzim

Or after: apt install libzim
Type this: 
export LD_LIBRARY_PATH="${LIBZIM_DIR}/lib:$LD_LIBRARY_PATH"

Then:
pip install libzim

Thanks
