### ISSUE TITLE
python-libzim not available on dockerhub

### ISSUE THREAD

**Issue by amirouche** [openzim/python-libzim#80]
The following command found in pypi.org page will fail

```
% docker run --rm -it openzim:python-libzim
Unable to find image 'openzim:python-libzim' locally
docker: Error response from daemon: pull access denied for openzim, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
See 'docker run --help'.
%
```

Apparantly the image is not public or not available.

**Comment by rgaudin** [comment]
Thanks for the report. It's a documentation issue, we don't provide a docker image. We'll remove that from doc.

**Comment by kelson42** [comment]
This has been removed from the README.md, see https://github.com/openzim/python-libzim/commit/ca0ed0c8a7deb85caf6cbcf9db3ee3e77c015632#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5. Will be available in January in next Pypi release.
