### ISSUE TITLE
wildcard search or an iterator over all pages

### ISSUE THREAD

**Issue by amirouche** [openzim/python-libzim#81]
More on more people are asking how to process wikipedia.  It seems to me .zim files are the best way to go.

It missing a way to go through the whole zim file. What I would expected is something along the lines of the following:

```python
for page in File("my.zim"):
    print(page.title)
```

Is it possible?

**Comment by kelson42** [comment]
Not python-libzim, but you should be able to do that with the `zimdump` tool.

**Comment by rgaudin** [comment]
It's there and easily guessable from the dosctring.

```py
with File("my.zim") as reader:
    for article_id in range(0, reader.article_count):
        page = reader.get_article_by_id(article_id)
```
