### ISSUE TITLE
Iterate over all articles efficiently

### ISSUE THREAD

**Issue by opk12** [openzim/python-libzim#83]
Issue #300 and PR #301 added support to iterate over all articles in the order they are stored in the file, for performance reasons. How to use it through the python bindings?

**Comment by kelson42** [comment]
I guess this is this which is meant https://github.com/openzim/libzim/issues/300

**Comment by mgautierfr** [comment]
This will be probably available with the new api of python-libzim (porting to the new api of libzim)

**Comment by rgaudin** [comment]
Closing this in favor of #94
