### ISSUE TITLE
python-libzim 0.0.3 segfaults when used with an updated libzim 6.3.0

### ISSUE THREAD

**Issue by legoktm** [openzim/python-libzim#84]
In Debian, python-libzim was initially built against libzim 6.2.2. Yesterday I updated libzim to 6.3.0, with no rebuild for python-libzim, and now the python-libzim test suite segfaults:

```
root@16589ef33bfe:/srv/python-libzim/tests# python3 -m pytest
=============================================== test session starts ===============================================
platform linux -- Python 3.8.6, pytest-4.6.11, py-1.9.0, pluggy-0.13.0
rootdir: /srv/python-libzim
collected 20 items                                                                                                

test_libzim.py Segmentation fault (core dumped)
```

https://gist.github.com/legoktm/ef86b76242e853d53826d4e885391c03 is the beginning of the backtrace. I can provide full reproduction steps for a docker container if that's needed.

If I rebuild python-libzim against libzim 6.3.0, then it's all fine. But I expect that because there was no ABI bump in libzim, that updating it shouldn't cause any problems for python-libzim. Is that assumption wrong?

**Comment by legoktm** [comment]
Thanks for the explanation. I rebuilt the Debian package for now, so it's no longer an issue for me. I'll leave it up to you whether to close this or leave it open for "..the wrapper code that doesn't catch this exception correctly."

**Comment by mgautierfr** [comment]
With the work of adaptation on libzim_next I will rework this. I will close the issue then.

**Comment by kelson42** [comment]
@mgautierfr Is this fixed with #82?

**Comment by kelson42** [comment]
@rgaudin @legoktm @mgautierfr I propose to close this ticket as the new python-libzim 1.0.0 to be published will work only and is tested against libzim7+. Does that sounds good to you?

**Comment by legoktm** [comment]
This isn't an issue for me from the Debian side, it was fixed when I rebuilt the package.

**Comment by mgautierfr** [comment]
Yes, we can close it.
We will change a lot of things soon and this issue will be somehow obsolete. As it is not a issue for @legoktm, let's close it.
