### ISSUE TITLE
Run CI on nightly version of libzim.

### ISSUE THREAD

**Issue by mgautierfr** [openzim/python-libzim#86]
We are running the CI using the official release of libzim.

I don't remember what was the rational behind this but I remember there were one :)

However, for big changes like libzim_next we will probably not release libzim before being sure that using project correctly works. This means that we need to be able to run the CI on the nightly build instead of the official release of libzim.

Maybe we can move the test workflow to the nightlybuild (but we need a stable url to download them) and keep the realese workflow on the official release of libzim ?

This is needed for the PR #82

**Comment by rgaudin** [comment]
This ticket is now obsolete. We are indeed testing from **a** nightly version on master, until libzim7 is released. Once this is done, we'll come back to the official release.
