### ISSUE TITLE
Support Python 3.9

### ISSUE THREAD

**Issue by kelson42** [openzim/python-libzim#89]
.. and update Cython version.

**Comment by rgaudin** [comment]
[Cython](https://pypi.org/project/Cython/) doesn't support py39 for the moment. Marking this as upstream.

**Comment by sobaee** [comment]
Any hope of supporting python 3.9 🤔?

**Comment by rgaudin** [comment]
I see that Cython 0.29.22 has py39 support so this is no longer upstream. Thanks for the heads up.

**Comment by rgaudin** [comment]
```
==================================================== test session starts =====================================================
platform darwin -- Python 3.9.0, pytest-6.2.2, py-1.10.0, pluggy-0.13.1
rootdir: /Users/reg/src/pylibzim
plugins: cov-2.11.1
collected 83 items

tests/test_libzim_creator.py ............................................                                              [ 53%]
tests/test_libzim_reader.py .......................................                                                    [100%]

---------- coverage: platform darwin, python 3.9.0-final-0 -----------
Name                 Stmts   Miss  Cover   Missing
--------------------------------------------------
libzim/__init__.py       0      0   100%
libzim/reader.py         2      0   100%
libzim/wrapper.pyx     234     11    95%   85, 89, 125-134
libzim/writer.py        72      0   100%
--------------------------------------------------
TOTAL                  308     11    96%
```

**Comment by sobaee** [comment]
> I see that Cython 0.29.22 has py39 support so this is no longer upstream. Thanks for the heads up.

What about libzim 🤔

**Comment by rgaudin** [comment]
> > I see that Cython 0.29.22 has py39 support so this is no longer upstream. Thanks for the heads up.
> 
> What about libzim 🤔

????? #101

**Comment by sobaee** [comment]
Great, many thanks
Will this change be available by "pip install libzim" also?
Or should I use git to do that?

**Comment by sobaee** [comment]
Hello developers

Please fix the version in Pypi to be installed in python 3.9

Currently "pip install libzim" is only success with python 3.8 (I tried with python 3.9 but failed)

And I can't get it worked either by git cloning.

Sorry 🙏
