### ISSUE TITLE
Support getHints

### ISSUE THREAD

**Issue by rgaudin** [openzim/python-libzim#93]
This applies to `libzim_next`.

Libzim supports `Item::getHints()` to provide a Hint map informing libzim about what to do with data.

At the moment, there is already the `COMPRESS` key which informs about whether to compress content or not.

Defaults to compressing if mimetype is in `zim::isCompressibleMimetype()`

We should support similar feature, probably on `Item.get_hints()`.

**Comment by mgautierfr** [comment]
The is even more needed as next libzim master will add `FRONT_ARTICLE` hint to tell if we must handle the item as a a front article (suggestion, random, ...) or not.
If we don't handle this, all items will **not** be front article.

**Comment by kelson42** [comment]
@mgautierfr I believe this would be a good time to finish the pylibzim
