### ISSUE TITLE
Add equality operator to Entry and Item

### ISSUE THREAD

**Issue by rgaudin** [openzim/python-libzim#96]
Currently we don't have `__eq__` on neither Archive, not Entry nor Item. This makes testing equivalence tedious as `==` always returns False since two entries would not share same address space.

Use case:

```py
assert zim.get_entry_by_path("dest") == zim.get_entry_by_path("redir").get_redirect_entry()
```

@mgautierfr what would be the `__eq__` code?

- same `.filename` for `Archive` ?
- same `.path` and `.title` for Entry? Problem is path abstract namespace and we have no access to the namespace. Also, we are removing access to `.index`…
- same `.path` and `.title` for Item? Would that be enough?

**Comment by mgautierfr** [comment]
> same .filename for Archive ?

Yes, but we must care that we use absolute path and "split resolved" path.
`Archive("foo.zim") == Archive("/home/user/bar/foo.zimaa")`

But I'm not sure we need this. Do we want to compare two `Archive`s ?

> same .path and .title for Entry? Problem is path abstract namespace and we have no access to the namespace. Also, we are removing access to .index…
> same .path and .title for Item? Would that be enough?

Index is probably the thing to compare. Even if we don't expose it publicly, we can use it internally.
Else, the path is enough has we ensure it is unique (except for pretty old zim files but it should be ok).
We must also be sure that Entry/Item come from the same Archive.

**Comment by rgaudin** [comment]
Added `Archive.__eq__` in 4a97218 (exception handling might be overkill though) but I couldn't go further with Entry as Entry object is not aware of its Archive.

The (unexposed) `c_entry` object does have a (private) `file_` but can this be leveraged to get the Archive's UUID or checksum?
